name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # get full commit history
      - name: Test plugin locally
        uses: asdf-vm/actions/plugin-test@v4
        with:
          plugin: tig
          giturl: https://github.com/jonas/tig
          gitref: master
          command: tig --help
